# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_CategoricalCN <- function(Probs) {
    .Call(`_SigPoisProcess_sample_CategoricalCN`, Probs)
}

sample_RCN <- function(R, W, SigPrior, channel_id) {
    .Call(`_SigPoisProcess_sample_RCN`, R, W, SigPrior, channel_id)
}

sample_ThetaCN <- function(Theta, Betas, SignalTrack, CopyTrack_t, CopyTot, W, Mu, a, sample_id) {
    .Call(`_SigPoisProcess_sample_ThetaCN`, Theta, Betas, SignalTrack, CopyTrack_t, CopyTot, W, Mu, a, sample_id)
}

sample_MuCN <- function(Theta, a, a0, b0, CopyTot) {
    .Call(`_SigPoisProcess_sample_MuCN`, Theta, a, a0, b0, CopyTot)
}

sample_Sigma2CN <- function(Betas, c0, d0) {
    .Call(`_SigPoisProcess_sample_Sigma2CN`, Betas, c0, d0)
}

sample_BetasCN <- function(Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples) {
    .Call(`_SigPoisProcess_sample_BetasCN`, Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples)
}

update_Mutation_assignementCN <- function(W, Probs) {
    invisible(.Call(`_SigPoisProcess_update_Mutation_assignementCN`, W, Probs))
}

update_Signatures_RCN <- function(R, W, SigPrior, Alpha, channel_indices) {
    invisible(.Call(`_SigPoisProcess_update_Signatures_RCN`, R, W, SigPrior, Alpha, channel_indices))
}

update_Activities_ThetaCN <- function(Theta, ExpBetaSignal, CopyTrack_t, CopyTot, W, Mu, Smat, a, sample_indices) {
    invisible(.Call(`_SigPoisProcess_update_Activities_ThetaCN`, Theta, ExpBetaSignal, CopyTrack_t, CopyTot, W, Mu, Smat, a, sample_indices))
}

update_RelevanceWeights_MuCN <- function(Mu, Theta, CopyTot, a, a0, b0) {
    invisible(.Call(`_SigPoisProcess_update_RelevanceWeights_MuCN`, Mu, Theta, CopyTot, a, a0, b0))
}

update_Variances_Sigma2 <- function(Sigma2, Betas, c0, d0) {
    invisible(.Call(`_SigPoisProcess_update_Variances_Sigma2`, Sigma2, Betas, c0, d0))
}

EllipticalSlice <- function(k, beta0, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t) {
    .Call(`_SigPoisProcess_EllipticalSlice`, k, beta0, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t)
}

update_Betas_EllipticalSlice <- function(Betas, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t) {
    invisible(.Call(`_SigPoisProcess_update_Betas_EllipticalSlice`, Betas, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t))
}

.PoissonProcess_BayesCN <- function(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, a = 1.1, a0 = 2.5, b0 = 1.5, c0 = 100, d0 = 1, verbose = FALSE) {
    .Call(`_SigPoisProcess_PoissonProcess_BayesCN`, R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R, update_Theta, update_Betas, a, a0, b0, c0, d0, verbose)
}

.PoissonProcess_optim_CN <- function(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, channel_id, sample_id, SigPrior, method = "map", shrinkage = "mu_sigma", a = 1.1, a0 = 2.5, b0 = 1.5, c0 = 100, d0 = 1, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, n_iter_betas = 2L, rho = 0.5, maxiter = 20L, tol = 1e-6, correct_betas = FALSE, verbose = FALSE) {
    .Call(`_SigPoisProcess_PoissonProcess_optim_CN`, R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, channel_id, sample_id, SigPrior, method, shrinkage, a, a0, b0, c0, d0, update_R, update_Theta, update_Betas, n_iter_betas, rho, maxiter, tol, correct_betas, verbose)
}

Reconstruct_Lambda <- function(SignalTrack, CopyTrack, R, Theta, Betas, verbose = FALSE) {
    .Call(`_SigPoisProcess_Reconstruct_Lambda`, SignalTrack, CopyTrack, R, Theta, Betas, verbose)
}

Reconstruct_CountMatrix <- function(SignalTrack, CopyTrack, R, Theta, Betas) {
    .Call(`_SigPoisProcess_Reconstruct_CountMatrix`, SignalTrack, CopyTrack, R, Theta, Betas)
}

sample_table_cpp <- function(tab) {
    .Call(`_SigPoisProcess_sample_table_cpp`, tab)
}

sample_Counts_cpp <- function(X, R, Betas, channel_Id, sample_Id) {
    .Call(`_SigPoisProcess_sample_Counts_cpp`, X, R, Betas, channel_Id, sample_Id)
}

calculate_Sig_covariate_prob <- function(X, R, Betas, channel_id, sample_id) {
    .Call(`_SigPoisProcess_calculate_Sig_covariate_prob`, X, R, Betas, channel_id, sample_id)
}

