# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Update_Phi <- function(Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id) {
    invisible(.Call('_SigPoisProcess_Update_Phi', PACKAGE = 'SigPoisProcess', Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id))
}

Update_alpha_r <- function(alpha_r, Phi, channel_id, sample_id, SigPrior) {
    invisible(.Call('_SigPoisProcess_Update_alpha_r', PACKAGE = 'SigPoisProcess', alpha_r, Phi, channel_id, sample_id, SigPrior))
}

Update_ab_beta <- function(a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar) {
    invisible(.Call('_SigPoisProcess_Update_ab_beta', PACKAGE = 'SigPoisProcess', a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar))
}

Update_ab_mu <- function(a_mu, b_mu, a_beta, b_beta, a, a0, b0) {
    invisible(.Call('_SigPoisProcess_Update_ab_mu', PACKAGE = 'SigPoisProcess', a_mu, b_mu, a_beta, b_beta, a, a0, b0))
}

InhomogeneousPoissonNMF_CAVI <- function(Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter = 200L, tol = 1e-6) {
    .Call('_SigPoisProcess_InhomogeneousPoissonNMF_CAVI', PACKAGE = 'SigPoisProcess', Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter, tol)
}

build_X_field <- function(X, I, J, channel_id, sample_id) {
    .Call('_SigPoisProcess_build_X_field', PACKAGE = 'SigPoisProcess', X, I, J, channel_id, sample_id)
}

Update_Signatures_MAP <- function(R, Betas, SigPrior, Xfield) {
    .Call('_SigPoisProcess_Update_Signatures_MAP', PACKAGE = 'SigPoisProcess', R, Betas, SigPrior, Xfield)
}

Update_Signatures_MAP2 <- function(R, Betas, SigPrior, X, channel_id, sample_id) {
    .Call('_SigPoisProcess_Update_Signatures_MAP2', PACKAGE = 'SigPoisProcess', R, Betas, SigPrior, X, channel_id, sample_id)
}

Update_Betas_MAP <- function(R, Betas, Mu, a, Xfield, X_bar, scaled = TRUE) {
    .Call('_SigPoisProcess_Update_Betas_MAP', PACKAGE = 'SigPoisProcess', R, Betas, Mu, a, Xfield, X_bar, scaled)
}

Update_Betas_MAP2 <- function(R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled = TRUE) {
    .Call('_SigPoisProcess_Update_Betas_MAP2', PACKAGE = 'SigPoisProcess', R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled)
}

Update_Mu <- function(Betas, X_bar, a, a0, b0, scaled = TRUE) {
    .Call('_SigPoisProcess_Update_Mu', PACKAGE = 'SigPoisProcess', Betas, X_bar, a, a0, b0, scaled)
}

compute_SigPoisProcess_logPost <- function(Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled = TRUE) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_logPost', PACKAGE = 'SigPoisProcess', Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled)
}

compute_SigPoisProcess_logPost2 <- function(X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled = TRUE) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_logPost2', PACKAGE = 'SigPoisProcess', X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled)
}

merge_similar_signatures <- function(R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge = 0.9, scaled = TRUE) {
    invisible(.Call('_SigPoisProcess_merge_similar_signatures', PACKAGE = 'SigPoisProcess', R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge, scaled))
}

compute_SigPoisProcess_MAP <- function(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6, scaled = TRUE, merge_move = TRUE, cutoff_merge = 0.9) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_MAP', PACKAGE = 'SigPoisProcess', R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled, merge_move, cutoff_merge)
}

compute_SigPoisProcess_MAP_Nest <- function(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6, scaled = TRUE) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_MAP_Nest', PACKAGE = 'SigPoisProcess', R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled)
}

Update_Signatures_MLE <- function(R, Betas, Xfield) {
    .Call('_SigPoisProcess_Update_Signatures_MLE', PACKAGE = 'SigPoisProcess', R, Betas, Xfield)
}

Update_Betas_MLE <- function(R, Betas, Xfield, X_bar) {
    .Call('_SigPoisProcess_Update_Betas_MLE', PACKAGE = 'SigPoisProcess', R, Betas, Xfield, X_bar)
}

compute_SigPoisProcess_logLik <- function(Xfield, R, Betas, X_bar) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_logLik', PACKAGE = 'SigPoisProcess', Xfield, R, Betas, X_bar)
}

compute_SigPoisProcess_MLE <- function(R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6) {
    .Call('_SigPoisProcess_compute_SigPoisProcess_MLE', PACKAGE = 'SigPoisProcess', R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter, tol)
}

eval_logPosterior <- function(X, R, Theta, Mu, a, a0, b0, SigPrior) {
    .Call('_SigPoisProcess_eval_logPosterior', PACKAGE = 'SigPoisProcess', X, R, Theta, Mu, a, a0, b0, SigPrior)
}

compute_CompressiveNMF_MAP <- function(X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence = FALSE) {
    .Call('_SigPoisProcess_compute_CompressiveNMF_MAP', PACKAGE = 'SigPoisProcess', X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence)
}

sample_table_cpp <- function(tab) {
    .Call('_SigPoisProcess_sample_table_cpp', PACKAGE = 'SigPoisProcess', tab)
}

sample_Counts_cpp <- function(X, R, Betas, channel_Id, sample_Id) {
    .Call('_SigPoisProcess_sample_Counts_cpp', PACKAGE = 'SigPoisProcess', X, R, Betas, channel_Id, sample_Id)
}

calculate_Sig_covariate_prob <- function(X, R, Betas, channel_id, sample_id) {
    .Call('_SigPoisProcess_calculate_Sig_covariate_prob', PACKAGE = 'SigPoisProcess', X, R, Betas, channel_id, sample_id)
}

