# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Update_Phi <- function(Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id) {
    invisible(.Call(`_SigPoisProcess_Update_Phi`, Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id))
}

Update_alpha_r <- function(alpha_r, Phi, channel_id, sample_id, SigPrior) {
    invisible(.Call(`_SigPoisProcess_Update_alpha_r`, alpha_r, Phi, channel_id, sample_id, SigPrior))
}

Update_ab_beta <- function(a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar) {
    invisible(.Call(`_SigPoisProcess_Update_ab_beta`, a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar))
}

Update_ab_mu <- function(a_mu, b_mu, a_beta, b_beta, a, a0, b0) {
    invisible(.Call(`_SigPoisProcess_Update_ab_mu`, a_mu, b_mu, a_beta, b_beta, a, a0, b0))
}

InhomogeneousPoissonNMF_CAVI <- function(Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter = 200L, tol = 1e-6) {
    .Call(`_SigPoisProcess_InhomogeneousPoissonNMF_CAVI`, Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter, tol)
}

build_X_field <- function(X, I, J, channel_id, sample_id) {
    .Call(`_SigPoisProcess_build_X_field`, X, I, J, channel_id, sample_id)
}

Update_Signatures_MAP <- function(R, Betas, SigPrior, Xfield) {
    .Call(`_SigPoisProcess_Update_Signatures_MAP`, R, Betas, SigPrior, Xfield)
}

Update_Signatures_MAP2 <- function(R, Betas, SigPrior, X, channel_id, sample_id) {
    .Call(`_SigPoisProcess_Update_Signatures_MAP2`, R, Betas, SigPrior, X, channel_id, sample_id)
}

Update_Betas_MAP <- function(R, Betas, Mu, a, Xfield, X_bar, scaled = TRUE) {
    .Call(`_SigPoisProcess_Update_Betas_MAP`, R, Betas, Mu, a, Xfield, X_bar, scaled)
}

Update_Betas_MAP2 <- function(R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled = TRUE) {
    .Call(`_SigPoisProcess_Update_Betas_MAP2`, R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled)
}

Update_Mu <- function(Betas, X_bar, a, a0, b0, scaled = TRUE, compress_sig_cov = TRUE) {
    .Call(`_SigPoisProcess_Update_Mu`, Betas, X_bar, a, a0, b0, scaled, compress_sig_cov)
}

compute_SigPoisProcess_logPost <- function(Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled = TRUE) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_logPost`, Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled)
}

compute_SigPoisProcess_logPost2 <- function(X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled = TRUE) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_logPost2`, X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled)
}

merge_similar_signatures <- function(R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge = 0.9, scaled = TRUE) {
    invisible(.Call(`_SigPoisProcess_merge_similar_signatures`, R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge, scaled))
}

compute_SigPoisProcess_MAP <- function(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6, scaled = TRUE, merge_move = TRUE, cutoff_merge = 0.9, compress_sig_cov = TRUE) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_MAP`, R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled, merge_move, cutoff_merge, compress_sig_cov)
}

compute_SigPoisProcess_MAP_Nest <- function(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6, scaled = TRUE) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_MAP_Nest`, R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled)
}

Update_Signatures_MLE <- function(R, Betas, Xfield) {
    .Call(`_SigPoisProcess_Update_Signatures_MLE`, R, Betas, Xfield)
}

Update_Betas_MLE <- function(R, Betas, Xfield, X_bar) {
    .Call(`_SigPoisProcess_Update_Betas_MLE`, R, Betas, Xfield, X_bar)
}

compute_SigPoisProcess_logLik <- function(Xfield, R, Betas, X_bar) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_logLik`, Xfield, R, Betas, X_bar)
}

compute_SigPoisProcess_MLE <- function(R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter = 1e6L, tol = 1e-6) {
    .Call(`_SigPoisProcess_compute_SigPoisProcess_MLE`, R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter, tol)
}

build_X_field2 <- function(X, I, J, channel_id, sample_id) {
    .Call(`_SigPoisProcess_build_X_field2`, X, I, J, channel_id, sample_id)
}

compute_expXtB_field <- function(X, I, J, channel_id, sample_id, Betas) {
    .Call(`_SigPoisProcess_compute_expXtB_field`, X, I, J, channel_id, sample_id, Betas)
}

Update_Signatures_MLE_loglinear2 <- function(R, Theta, Betas, X, channel_id, sample_id) {
    .Call(`_SigPoisProcess_Update_Signatures_MLE_loglinear2`, R, Theta, Betas, X, channel_id, sample_id)
}

Update_Theta_MLE_loglinear <- function(R, Theta, Betas, X, channel_id, sample_id, Xtotal, Bins) {
    .Call(`_SigPoisProcess_Update_Theta_MLE_loglinear`, R, Theta, Betas, X, channel_id, sample_id, Xtotal, Bins)
}

Update_Theta_Betas_loglinear <- function(R, Theta, Betas_start, X, channel_id, sample_id, Xtotal, Bins, iter = 30L) {
    .Call(`_SigPoisProcess_Update_Theta_Betas_loglinear`, R, Theta, Betas_start, X, channel_id, sample_id, Xtotal, Bins, iter)
}

PPF_loglinear <- function(R_start, Theta_start, Betas_start, Mu_start, X, channel_id, sample_id, Xtotal, Bins, SigPrior, a, a0, b0, epsilon, method = "mle", update_Sigs = TRUE, maxiter = 1000L, tol = 1e-5) {
    .Call(`_SigPoisProcess_PPF_loglinear`, R_start, Theta_start, Betas_start, Mu_start, X, channel_id, sample_id, Xtotal, Bins, SigPrior, a, a0, b0, epsilon, method, update_Sigs, maxiter, tol)
}

sample_Categorical <- function(Probs) {
    .Call(`_SigPoisProcess_sample_Categorical`, Probs)
}

sample_R <- function(R, W, SigPrior, channel_id) {
    .Call(`_SigPoisProcess_sample_R`, R, W, SigPrior, channel_id)
}

sample_Theta <- function(Theta, Betas, SignalTrack, bin_weight, W, Mu, a, sample_id) {
    .Call(`_SigPoisProcess_sample_Theta`, Theta, Betas, SignalTrack, bin_weight, W, Mu, a, sample_id)
}

sample_Mu <- function(Theta, Betas, a, a0, b0, Ttot) {
    .Call(`_SigPoisProcess_sample_Mu`, Theta, Betas, a, a0, b0, Ttot)
}

sample_Betas <- function(Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples) {
    .Call(`_SigPoisProcess_sample_Betas`, Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples)
}

sample_Betas_MALA <- function(Betas_start, W, X, SignalTrack, Theta, bin_weight, PrecondSigma, Mu, nsamples, eps_step = 1) {
    .Call(`_SigPoisProcess_sample_Betas_MALA`, Betas_start, W, X, SignalTrack, Theta, bin_weight, PrecondSigma, Mu, nsamples, eps_step)
}

update_Mutation_assignement <- function(W, Probs) {
    invisible(.Call(`_SigPoisProcess_update_Mutation_assignement`, W, Probs))
}

update_Signatures_R <- function(R, W, SigPrior, Alpha, channel_indices) {
    invisible(.Call(`_SigPoisProcess_update_Signatures_R`, R, W, SigPrior, Alpha, channel_indices))
}

update_Loadings_Theta <- function(Theta, Betas, ExpBetaSignal, bin_weight, W, Mu, Smat, theta_denom, a, Ttot, sample_indices) {
    invisible(.Call(`_SigPoisProcess_update_Loadings_Theta`, Theta, Betas, ExpBetaSignal, bin_weight, W, Mu, Smat, theta_denom, a, Ttot, sample_indices))
}

update_RelevanceWeights_Mu <- function(Mu, Theta, Betas, Betasq, Theta_sum, a, a0, b0, Ttot) {
    invisible(.Call(`_SigPoisProcess_update_RelevanceWeights_Mu`, Mu, Theta, Betas, Betasq, Theta_sum, a, a0, b0, Ttot))
}

update_Betas_coefficients <- function(Betas, W, Mu, Theta, X, SignalTrack, bw, betadiff, Theta_sum, it, beta_new, S, Sigmas_adp, MeanBetas, WtX) {
    invisible(.Call(`_SigPoisProcess_update_Betas_coefficients`, Betas, W, Mu, Theta, X, SignalTrack, bw, betadiff, Theta_sum, it, beta_new, S, Sigmas_adp, MeanBetas, WtX))
}

update_Betas_coefficients_MALA <- function(Betas, WtX, SignalTrack, Theta_sum, beta_new, bin_weight, bw, Mu, eps_step, ExpBetaSignal, ExpSignalBeta_new, PrecondSigma, Cholesky, Inverse, logGrad_old, logGrad_new) {
    invisible(.Call(`_SigPoisProcess_update_Betas_coefficients_MALA`, Betas, WtX, SignalTrack, Theta_sum, beta_new, bin_weight, bw, Mu, eps_step, ExpBetaSignal, ExpSignalBeta_new, PrecondSigma, Cholesky, Inverse, logGrad_old, logGrad_new))
}

.PoissonProcess_Bayes_MALA <- function(R_start, Theta_start, Betas_start, Mu_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, PrecondSigma, eps_step = 1.2, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, a = 1.1, a0 = 2.5, b0 = 1.5) {
    .Call(`_SigPoisProcess_PoissonProcess_Bayes_MALA`, R_start, Theta_start, Betas_start, Mu_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, PrecondSigma, eps_step, update_R, update_Theta, update_Betas, a, a0, b0)
}

.PoissonProcess_Bayes <- function(R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, a = 1.1, a0 = 2.5, b0 = 1.5) {
    .Call(`_SigPoisProcess_PoissonProcess_Bayes`, R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R, update_Theta, update_Betas, a, a0, b0)
}

sample_CategoricalCN <- function(Probs) {
    .Call(`_SigPoisProcess_sample_CategoricalCN`, Probs)
}

sample_RCN <- function(R, W, SigPrior, channel_id) {
    .Call(`_SigPoisProcess_sample_RCN`, R, W, SigPrior, channel_id)
}

sample_ThetaCN <- function(Theta, Betas, SignalTrack, CopyTrack_t, CopyTot, W, Mu, a, sample_id) {
    .Call(`_SigPoisProcess_sample_ThetaCN`, Theta, Betas, SignalTrack, CopyTrack_t, CopyTot, W, Mu, a, sample_id)
}

sample_MuCN <- function(Theta, a, a0, b0, CopyTot) {
    .Call(`_SigPoisProcess_sample_MuCN`, Theta, a, a0, b0, CopyTot)
}

sample_Sigma2CN <- function(Betas, c0, d0) {
    .Call(`_SigPoisProcess_sample_Sigma2CN`, Betas, c0, d0)
}

sample_BetasCN <- function(Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples) {
    .Call(`_SigPoisProcess_sample_BetasCN`, Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples)
}

update_Mutation_assignementCN <- function(W, Probs) {
    invisible(.Call(`_SigPoisProcess_update_Mutation_assignementCN`, W, Probs))
}

update_Signatures_RCN <- function(R, W, SigPrior, Alpha, channel_indices) {
    invisible(.Call(`_SigPoisProcess_update_Signatures_RCN`, R, W, SigPrior, Alpha, channel_indices))
}

update_Activities_ThetaCN <- function(Theta, ExpBetaSignal, CopyTrack_t, CopyTot, W, Mu, Smat, a, sample_indices) {
    invisible(.Call(`_SigPoisProcess_update_Activities_ThetaCN`, Theta, ExpBetaSignal, CopyTrack_t, CopyTot, W, Mu, Smat, a, sample_indices))
}

update_RelevanceWeights_MuCN <- function(Mu, Theta, CopyTot, a, a0, b0) {
    invisible(.Call(`_SigPoisProcess_update_RelevanceWeights_MuCN`, Mu, Theta, CopyTot, a, a0, b0))
}

update_Variances_Sigma2 <- function(Sigma2, Betas, c0, d0) {
    invisible(.Call(`_SigPoisProcess_update_Variances_Sigma2`, Sigma2, Betas, c0, d0))
}

EllipticalSlice <- function(k, beta0, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t) {
    .Call(`_SigPoisProcess_EllipticalSlice`, k, beta0, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t)
}

update_Betas_EllipticalSlice <- function(Betas, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t) {
    invisible(.Call(`_SigPoisProcess_update_Betas_EllipticalSlice`, Betas, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t))
}

.PoissonProcess_BayesCN <- function(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, a = 1.1, a0 = 2.5, b0 = 1.5, c0 = 100, d0 = 1) {
    .Call(`_SigPoisProcess_PoissonProcess_BayesCN`, R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R, update_Theta, update_Betas, a, a0, b0, c0, d0)
}

.PoissonProcess_optim <- function(R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, channel_id, sample_id, SigPrior, method = "map", shrinkage = "none", a = 1.1, a0 = 2.5, b0 = 1.5, c0 = 100, d0 = 1, rho = 5, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, n_iter_betas = 2L, maxiter = 20L, tol = 1e-6, correct_betas = FALSE) {
    .Call(`_SigPoisProcess_PoissonProcess_optim`, R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, channel_id, sample_id, SigPrior, method, shrinkage, a, a0, b0, c0, d0, rho, update_R, update_Theta, update_Betas, n_iter_betas, maxiter, tol, correct_betas)
}

.PoissonProcess_optim_CN <- function(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, channel_id, sample_id, SigPrior, method = "map", shrinkage = "mu_sigma", a = 1.1, a0 = 2.5, b0 = 1.5, c0 = 100, d0 = 1, update_R = TRUE, update_Theta = TRUE, update_Betas = TRUE, n_iter_betas = 2L, rho = 0.5, maxiter = 20L, tol = 1e-6, correct_betas = FALSE) {
    .Call(`_SigPoisProcess_PoissonProcess_optim_CN`, R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, channel_id, sample_id, SigPrior, method, shrinkage, a, a0, b0, c0, d0, update_R, update_Theta, update_Betas, n_iter_betas, rho, maxiter, tol, correct_betas)
}

Reconstruct_Lambda <- function(SignalTrack, CopyTrack, R, Theta, Betas) {
    .Call(`_SigPoisProcess_Reconstruct_Lambda`, SignalTrack, CopyTrack, R, Theta, Betas)
}

Reconstruct_CountMatrix <- function(SignalTrack, CopyTrack, R, Theta, Betas) {
    .Call(`_SigPoisProcess_Reconstruct_CountMatrix`, SignalTrack, CopyTrack, R, Theta, Betas)
}

eval_logPosterior <- function(X, R, Theta, Mu, a, a0, b0, SigPrior) {
    .Call(`_SigPoisProcess_eval_logPosterior`, X, R, Theta, Mu, a, a0, b0, SigPrior)
}

compute_CompressiveNMF_MAP <- function(X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence = FALSE) {
    .Call(`_SigPoisProcess_compute_CompressiveNMF_MAP`, X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence)
}

sample_table_cpp <- function(tab) {
    .Call(`_SigPoisProcess_sample_table_cpp`, tab)
}

sample_Counts_cpp <- function(X, R, Betas, channel_Id, sample_Id) {
    .Call(`_SigPoisProcess_sample_Counts_cpp`, X, R, Betas, channel_Id, sample_Id)
}

calculate_Sig_covariate_prob <- function(X, R, Betas, channel_id, sample_id) {
    .Call(`_SigPoisProcess_calculate_Sig_covariate_prob`, X, R, Betas, channel_id, sample_id)
}

