// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Update_Phi
void Update_Phi(arma::cube& Phi, arma::mat& alpha_r, arma::cube& a_beta, arma::cube& b_beta, arma::mat& logX, arma::uvec& channel_id, arma::uvec& sample_id);
RcppExport SEXP _SigPoisProcess_Update_Phi(SEXP PhiSEXP, SEXP alpha_rSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP logXSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type logX(logXSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Update_Phi(Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id);
    return R_NilValue;
END_RCPP
}
// Update_alpha_r
void Update_alpha_r(arma::mat& alpha_r, arma::cube& Phi, arma::uvec& channel_id, arma::uvec& sample_id, arma::mat& SigPrior);
RcppExport SEXP _SigPoisProcess_Update_alpha_r(SEXP alpha_rSEXP, SEXP PhiSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Update_alpha_r(alpha_r, Phi, channel_id, sample_id, SigPrior);
    return R_NilValue;
END_RCPP
}
// Update_ab_beta
void Update_ab_beta(arma::cube& a_beta, arma::cube& b_beta, arma::cube& Phi, arma::mat& a_mu, arma::mat& b_mu, arma::uvec& channel_id, arma::uvec& sample_id, double a, arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_Update_ab_beta(SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP PhiSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP aSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type X_bar(X_barSEXP);
    Update_ab_beta(a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar);
    return R_NilValue;
END_RCPP
}
// Update_ab_mu
void Update_ab_mu(arma::mat& a_mu, arma::mat& b_mu, arma::cube& a_beta, arma::cube& b_beta, double a, double a0, double b0);
RcppExport SEXP _SigPoisProcess_Update_ab_mu(SEXP a_muSEXP, SEXP b_muSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Update_ab_mu(a_mu, b_mu, a_beta, b_beta, a, a0, b0);
    return R_NilValue;
END_RCPP
}
// InhomogeneousPoissonNMF_CAVI
List InhomogeneousPoissonNMF_CAVI(arma::cube& Phi, arma::mat& alpha_r, arma::cube& a_beta, arma::cube& b_beta, arma::mat& a_mu, arma::mat& b_mu, arma::mat& X, arma::cube& X_bar, arma::uvec& channel_id, arma::uvec& sample_id, arma::mat& SigPrior, double a, double a0, double b0, int maxiter, double tol);
RcppExport SEXP _SigPoisProcess_InhomogeneousPoissonNMF_CAVI(SEXP PhiSEXP, SEXP alpha_rSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(InhomogeneousPoissonNMF_CAVI(Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// build_X_field
arma::field<arma::mat> build_X_field(const arma::mat& X, arma::uword I, arma::uword J, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_build_X_field(SEXP XSEXP, SEXP ISEXP, SEXP JSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uword >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(build_X_field(X, I, J, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MAP
arma::mat Update_Signatures_MAP(arma::mat& R, arma::cube& Betas, const arma::mat& SigPrior, const arma::field<arma::mat>& Xfield);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MAP(SEXP RSEXP, SEXP BetasSEXP, SEXP SigPriorSEXP, SEXP XfieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MAP(R, Betas, SigPrior, Xfield));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MAP2
arma::mat Update_Signatures_MAP2(arma::mat& R, arma::cube& Betas, const arma::mat& SigPrior, arma::mat X, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MAP2(SEXP RSEXP, SEXP BetasSEXP, SEXP SigPriorSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MAP2(R, Betas, SigPrior, X, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MAP
arma::cube Update_Betas_MAP(arma::mat& R, arma::cube& Betas, arma::mat& Mu, double a, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar, bool scaled);
RcppExport SEXP _SigPoisProcess_Update_Betas_MAP(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP XfieldSEXP, SEXP X_barSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MAP(R, Betas, Mu, a, Xfield, X_bar, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MAP2
arma::cube Update_Betas_MAP2(arma::mat& R, arma::cube& Betas, arma::mat& Mu, double a, const arma::cube& X_bar, arma::mat X, arma::uvec channel_id, arma::uvec sample_id, bool scaled);
RcppExport SEXP _SigPoisProcess_Update_Betas_MAP2(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP X_barSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MAP2(R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Mu
arma::mat Update_Mu(arma::cube& Betas, const arma::cube& X_bar, double a, double a0, double b0, bool scaled);
RcppExport SEXP _SigPoisProcess_Update_Mu(SEXP BetasSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Mu(Betas, X_bar, a, a0, b0, scaled));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logPost
double compute_SigPoisProcess_logPost(const arma::field<arma::mat>& Xfield, arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logPost(SEXP XfieldSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logPost(Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logPost2
double compute_SigPoisProcess_logPost2(const arma::mat& X, arma::uvec channel_id, arma::uvec sample_id, arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logPost2(SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logPost2(X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled));
    return rcpp_result_gen;
END_RCPP
}
// merge_similar_signatures
void merge_similar_signatures(arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, double cutoff_merge, bool scaled);
RcppExport SEXP _SigPoisProcess_merge_similar_signatures(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP XfieldSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP cutoff_mergeSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_merge(cutoff_mergeSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    merge_similar_signatures(R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge, scaled);
    return R_NilValue;
END_RCPP
}
// compute_SigPoisProcess_MAP
List compute_SigPoisProcess_MAP(arma::mat R_start, arma::cube Betas_start, arma::mat Mu_start, arma::mat& SigPrior, double a, double a0, double b0, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol, bool scaled, bool merge_move, double cutoff_merge);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MAP(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP scaledSEXP, SEXP merge_moveSEXP, SEXP cutoff_mergeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    Rcpp::traits::input_parameter< bool >::type merge_move(merge_moveSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_merge(cutoff_mergeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MAP(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled, merge_move, cutoff_merge));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_MAP_Nest
List compute_SigPoisProcess_MAP_Nest(arma::mat R_start, arma::cube Betas_start, arma::mat Mu_start, arma::mat& SigPrior, double a, double a0, double b0, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MAP_Nest(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MAP_Nest(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MLE
arma::mat Update_Signatures_MLE(arma::mat& R, arma::cube& Betas, const arma::field<arma::mat>& Xfield);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MLE(SEXP RSEXP, SEXP BetasSEXP, SEXP XfieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MLE(R, Betas, Xfield));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MLE
arma::cube Update_Betas_MLE(arma::mat& R, arma::cube& Betas, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_Update_Betas_MLE(SEXP RSEXP, SEXP BetasSEXP, SEXP XfieldSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MLE(R, Betas, Xfield, X_bar));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logLik
double compute_SigPoisProcess_logLik(const arma::field<arma::mat>& Xfield, arma::mat& R, arma::cube& Betas, const arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logLik(SEXP XfieldSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logLik(Xfield, R, Betas, X_bar));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_MLE
List compute_SigPoisProcess_MLE(arma::mat R_start, arma::cube Betas_start, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MLE(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MLE(R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// eval_logPosterior
double eval_logPosterior(arma::mat& X, arma::mat& R, arma::mat& Theta, arma::vec& Mu, double a, double a0, double b0, arma::mat& SigPrior);
RcppExport SEXP _SigPoisProcess_eval_logPosterior(SEXP XSEXP, SEXP RSEXP, SEXP ThetaSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_logPosterior(X, R, Theta, Mu, a, a0, b0, SigPrior));
    return rcpp_result_gen;
END_RCPP
}
// compute_CompressiveNMF_MAP
List compute_CompressiveNMF_MAP(arma::mat X, arma::mat R_start, arma::mat Theta_start, arma::vec Mu_start, arma::mat& SigPrior, double a0, double b0, double a, int maxiter, double tol, bool use_logpost_for_convergence);
RcppExport SEXP _SigPoisProcess_compute_CompressiveNMF_MAP(SEXP XSEXP, SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP aSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP use_logpost_for_convergenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type use_logpost_for_convergence(use_logpost_for_convergenceSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_CompressiveNMF_MAP(X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence));
    return rcpp_result_gen;
END_RCPP
}
// sample_table_cpp
arma::uvec sample_table_cpp(arma::mat& tab);
RcppExport SEXP _SigPoisProcess_sample_table_cpp(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type tab(tabSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_table_cpp(tab));
    return rcpp_result_gen;
END_RCPP
}
// sample_Counts_cpp
List sample_Counts_cpp(arma::mat& X, arma::mat& R, arma::cube& Betas, arma::uvec& channel_Id, arma::uvec& sample_Id);
RcppExport SEXP _SigPoisProcess_sample_Counts_cpp(SEXP XSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP channel_IdSEXP, SEXP sample_IdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_Id(channel_IdSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_Id(sample_IdSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Counts_cpp(X, R, Betas, channel_Id, sample_Id));
    return rcpp_result_gen;
END_RCPP
}
// calculate_Sig_covariate_prob
List calculate_Sig_covariate_prob(arma::mat& X, arma::mat& R, arma::cube& Betas, arma::uvec& channel_id, arma::uvec& sample_id);
RcppExport SEXP _SigPoisProcess_calculate_Sig_covariate_prob(SEXP XSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_Sig_covariate_prob(X, R, Betas, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SigPoisProcess_Update_Phi", (DL_FUNC) &_SigPoisProcess_Update_Phi, 7},
    {"_SigPoisProcess_Update_alpha_r", (DL_FUNC) &_SigPoisProcess_Update_alpha_r, 5},
    {"_SigPoisProcess_Update_ab_beta", (DL_FUNC) &_SigPoisProcess_Update_ab_beta, 9},
    {"_SigPoisProcess_Update_ab_mu", (DL_FUNC) &_SigPoisProcess_Update_ab_mu, 7},
    {"_SigPoisProcess_InhomogeneousPoissonNMF_CAVI", (DL_FUNC) &_SigPoisProcess_InhomogeneousPoissonNMF_CAVI, 16},
    {"_SigPoisProcess_build_X_field", (DL_FUNC) &_SigPoisProcess_build_X_field, 5},
    {"_SigPoisProcess_Update_Signatures_MAP", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MAP, 4},
    {"_SigPoisProcess_Update_Signatures_MAP2", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MAP2, 6},
    {"_SigPoisProcess_Update_Betas_MAP", (DL_FUNC) &_SigPoisProcess_Update_Betas_MAP, 7},
    {"_SigPoisProcess_Update_Betas_MAP2", (DL_FUNC) &_SigPoisProcess_Update_Betas_MAP2, 9},
    {"_SigPoisProcess_Update_Mu", (DL_FUNC) &_SigPoisProcess_Update_Mu, 6},
    {"_SigPoisProcess_compute_SigPoisProcess_logPost", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logPost, 10},
    {"_SigPoisProcess_compute_SigPoisProcess_logPost2", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logPost2, 12},
    {"_SigPoisProcess_merge_similar_signatures", (DL_FUNC) &_SigPoisProcess_merge_similar_signatures, 11},
    {"_SigPoisProcess_compute_SigPoisProcess_MAP", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MAP, 16},
    {"_SigPoisProcess_compute_SigPoisProcess_MAP_Nest", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MAP_Nest, 14},
    {"_SigPoisProcess_Update_Signatures_MLE", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MLE, 3},
    {"_SigPoisProcess_Update_Betas_MLE", (DL_FUNC) &_SigPoisProcess_Update_Betas_MLE, 4},
    {"_SigPoisProcess_compute_SigPoisProcess_logLik", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logLik, 4},
    {"_SigPoisProcess_compute_SigPoisProcess_MLE", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MLE, 8},
    {"_SigPoisProcess_eval_logPosterior", (DL_FUNC) &_SigPoisProcess_eval_logPosterior, 8},
    {"_SigPoisProcess_compute_CompressiveNMF_MAP", (DL_FUNC) &_SigPoisProcess_compute_CompressiveNMF_MAP, 11},
    {"_SigPoisProcess_sample_table_cpp", (DL_FUNC) &_SigPoisProcess_sample_table_cpp, 1},
    {"_SigPoisProcess_sample_Counts_cpp", (DL_FUNC) &_SigPoisProcess_sample_Counts_cpp, 5},
    {"_SigPoisProcess_calculate_Sig_covariate_prob", (DL_FUNC) &_SigPoisProcess_calculate_Sig_covariate_prob, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SigPoisProcess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
