// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Update_Phi
void Update_Phi(arma::cube& Phi, arma::mat& alpha_r, arma::cube& a_beta, arma::cube& b_beta, arma::mat& logX, arma::uvec& channel_id, arma::uvec& sample_id);
RcppExport SEXP _SigPoisProcess_Update_Phi(SEXP PhiSEXP, SEXP alpha_rSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP logXSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type logX(logXSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Update_Phi(Phi, alpha_r, a_beta, b_beta, logX, channel_id, sample_id);
    return R_NilValue;
END_RCPP
}
// Update_alpha_r
void Update_alpha_r(arma::mat& alpha_r, arma::cube& Phi, arma::uvec& channel_id, arma::uvec& sample_id, arma::mat& SigPrior);
RcppExport SEXP _SigPoisProcess_Update_alpha_r(SEXP alpha_rSEXP, SEXP PhiSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Update_alpha_r(alpha_r, Phi, channel_id, sample_id, SigPrior);
    return R_NilValue;
END_RCPP
}
// Update_ab_beta
void Update_ab_beta(arma::cube& a_beta, arma::cube& b_beta, arma::cube& Phi, arma::mat& a_mu, arma::mat& b_mu, arma::uvec& channel_id, arma::uvec& sample_id, double a, arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_Update_ab_beta(SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP PhiSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP aSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type X_bar(X_barSEXP);
    Update_ab_beta(a_beta, b_beta, Phi, a_mu, b_mu, channel_id, sample_id, a, X_bar);
    return R_NilValue;
END_RCPP
}
// Update_ab_mu
void Update_ab_mu(arma::mat& a_mu, arma::mat& b_mu, arma::cube& a_beta, arma::cube& b_beta, double a, double a0, double b0);
RcppExport SEXP _SigPoisProcess_Update_ab_mu(SEXP a_muSEXP, SEXP b_muSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Update_ab_mu(a_mu, b_mu, a_beta, b_beta, a, a0, b0);
    return R_NilValue;
END_RCPP
}
// InhomogeneousPoissonNMF_CAVI
List InhomogeneousPoissonNMF_CAVI(arma::cube& Phi, arma::mat& alpha_r, arma::cube& a_beta, arma::cube& b_beta, arma::mat& a_mu, arma::mat& b_mu, arma::mat& X, arma::cube& X_bar, arma::uvec& channel_id, arma::uvec& sample_id, arma::mat& SigPrior, double a, double a0, double b0, int maxiter, double tol);
RcppExport SEXP _SigPoisProcess_InhomogeneousPoissonNMF_CAVI(SEXP PhiSEXP, SEXP alpha_rSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP a_muSEXP, SEXP b_muSEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type a_mu(a_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b_mu(b_muSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(InhomogeneousPoissonNMF_CAVI(Phi, alpha_r, a_beta, b_beta, a_mu, b_mu, X, X_bar, channel_id, sample_id, SigPrior, a, a0, b0, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// build_X_field
arma::field<arma::mat> build_X_field(const arma::mat& X, arma::uword I, arma::uword J, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_build_X_field(SEXP XSEXP, SEXP ISEXP, SEXP JSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uword >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(build_X_field(X, I, J, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MAP
arma::mat Update_Signatures_MAP(arma::mat& R, arma::cube& Betas, const arma::mat& SigPrior, const arma::field<arma::mat>& Xfield);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MAP(SEXP RSEXP, SEXP BetasSEXP, SEXP SigPriorSEXP, SEXP XfieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MAP(R, Betas, SigPrior, Xfield));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MAP2
arma::mat Update_Signatures_MAP2(arma::mat& R, arma::cube& Betas, const arma::mat& SigPrior, arma::mat X, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MAP2(SEXP RSEXP, SEXP BetasSEXP, SEXP SigPriorSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MAP2(R, Betas, SigPrior, X, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MAP
arma::cube Update_Betas_MAP(arma::mat& R, arma::cube& Betas, arma::mat& Mu, double a, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar, bool scaled);
RcppExport SEXP _SigPoisProcess_Update_Betas_MAP(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP XfieldSEXP, SEXP X_barSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MAP(R, Betas, Mu, a, Xfield, X_bar, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MAP2
arma::cube Update_Betas_MAP2(arma::mat& R, arma::cube& Betas, arma::mat& Mu, double a, const arma::cube& X_bar, arma::mat X, arma::uvec channel_id, arma::uvec sample_id, bool scaled);
RcppExport SEXP _SigPoisProcess_Update_Betas_MAP2(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP X_barSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MAP2(R, Betas, Mu, a, X_bar, X, channel_id, sample_id, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Mu
arma::mat Update_Mu(arma::cube& Betas, const arma::cube& X_bar, double a, double a0, double b0, bool scaled, bool compress_sig_cov);
RcppExport SEXP _SigPoisProcess_Update_Mu(SEXP BetasSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP scaledSEXP, SEXP compress_sig_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    Rcpp::traits::input_parameter< bool >::type compress_sig_cov(compress_sig_covSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Mu(Betas, X_bar, a, a0, b0, scaled, compress_sig_cov));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logPost
double compute_SigPoisProcess_logPost(const arma::field<arma::mat>& Xfield, arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logPost(SEXP XfieldSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logPost(Xfield, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logPost2
double compute_SigPoisProcess_logPost2(const arma::mat& X, arma::uvec channel_id, arma::uvec sample_id, arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logPost2(SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logPost2(X, channel_id, sample_id, R, Betas, Mu, X_bar, a, a0, b0, SigPrior, scaled));
    return rcpp_result_gen;
END_RCPP
}
// merge_similar_signatures
void merge_similar_signatures(arma::mat& R, arma::cube& Betas, arma::mat& Mu, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar, double a, double a0, double b0, arma::mat& SigPrior, double cutoff_merge, bool scaled);
RcppExport SEXP _SigPoisProcess_merge_similar_signatures(SEXP RSEXP, SEXP BetasSEXP, SEXP MuSEXP, SEXP XfieldSEXP, SEXP X_barSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP, SEXP cutoff_mergeSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_merge(cutoff_mergeSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    merge_similar_signatures(R, Betas, Mu, Xfield, X_bar, a, a0, b0, SigPrior, cutoff_merge, scaled);
    return R_NilValue;
END_RCPP
}
// compute_SigPoisProcess_MAP
List compute_SigPoisProcess_MAP(arma::mat R_start, arma::cube Betas_start, arma::mat Mu_start, arma::mat& SigPrior, double a, double a0, double b0, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol, bool scaled, bool merge_move, double cutoff_merge, bool compress_sig_cov);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MAP(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP scaledSEXP, SEXP merge_moveSEXP, SEXP cutoff_mergeSEXP, SEXP compress_sig_covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    Rcpp::traits::input_parameter< bool >::type merge_move(merge_moveSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff_merge(cutoff_mergeSEXP);
    Rcpp::traits::input_parameter< bool >::type compress_sig_cov(compress_sig_covSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MAP(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled, merge_move, cutoff_merge, compress_sig_cov));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_MAP_Nest
List compute_SigPoisProcess_MAP_Nest(arma::mat R_start, arma::cube Betas_start, arma::mat Mu_start, arma::mat& SigPrior, double a, double a0, double b0, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol, bool scaled);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MAP_Nest(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MAP_Nest(R_start, Betas_start, Mu_start, SigPrior, a, a0, b0, X, X_bar, channel_id, sample_id, maxiter, tol, scaled));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MLE
arma::mat Update_Signatures_MLE(arma::mat& R, arma::cube& Betas, const arma::field<arma::mat>& Xfield);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MLE(SEXP RSEXP, SEXP BetasSEXP, SEXP XfieldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MLE(R, Betas, Xfield));
    return rcpp_result_gen;
END_RCPP
}
// Update_Betas_MLE
arma::cube Update_Betas_MLE(arma::mat& R, arma::cube& Betas, const arma::field<arma::mat>& Xfield, const arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_Update_Betas_MLE(SEXP RSEXP, SEXP BetasSEXP, SEXP XfieldSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Betas_MLE(R, Betas, Xfield, X_bar));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_logLik
double compute_SigPoisProcess_logLik(const arma::field<arma::mat>& Xfield, arma::mat& R, arma::cube& Betas, const arma::cube& X_bar);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_logLik(SEXP XfieldSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP X_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Xfield(XfieldSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_logLik(Xfield, R, Betas, X_bar));
    return rcpp_result_gen;
END_RCPP
}
// compute_SigPoisProcess_MLE
List compute_SigPoisProcess_MLE(arma::mat R_start, arma::cube Betas_start, arma::mat& X, const arma::cube& X_bar, arma::uvec channel_id, arma::uvec sample_id, int maxiter, double tol);
RcppExport SEXP _SigPoisProcess_compute_SigPoisProcess_MLE(SEXP R_startSEXP, SEXP Betas_startSEXP, SEXP XSEXP, SEXP X_barSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type X_bar(X_barSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_SigPoisProcess_MLE(R_start, Betas_start, X, X_bar, channel_id, sample_id, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// build_X_field2
arma::field<arma::mat> build_X_field2(const arma::mat& X, arma::uword I, arma::uword J, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_build_X_field2(SEXP XSEXP, SEXP ISEXP, SEXP JSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uword >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(build_X_field2(X, I, J, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// compute_expXtB_field
arma::field<arma::mat> compute_expXtB_field(const arma::mat& X, arma::uword I, arma::uword J, arma::uvec channel_id, arma::uvec sample_id, arma::mat& Betas);
RcppExport SEXP _SigPoisProcess_compute_expXtB_field(SEXP XSEXP, SEXP ISEXP, SEXP JSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP BetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type I(ISEXP);
    Rcpp::traits::input_parameter< arma::uword >::type J(JSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_expXtB_field(X, I, J, channel_id, sample_id, Betas));
    return rcpp_result_gen;
END_RCPP
}
// Update_Signatures_MLE_loglinear2
arma::mat Update_Signatures_MLE_loglinear2(arma::mat& R, arma::mat& Theta, arma::mat& Betas, arma::mat X, arma::uvec channel_id, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_Update_Signatures_MLE_loglinear2(SEXP RSEXP, SEXP ThetaSEXP, SEXP BetasSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Signatures_MLE_loglinear2(R, Theta, Betas, X, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// Update_Theta_MLE_loglinear
arma::mat Update_Theta_MLE_loglinear(arma::mat& R, arma::mat& Theta, arma::mat& Betas, arma::mat& X, arma::uvec channel_id, arma::uvec sample_id, arma::cube& Xtotal, arma::mat& Bins);
RcppExport SEXP _SigPoisProcess_Update_Theta_MLE_loglinear(SEXP RSEXP, SEXP ThetaSEXP, SEXP BetasSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP XtotalSEXP, SEXP BinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Xtotal(XtotalSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Bins(BinsSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Theta_MLE_loglinear(R, Theta, Betas, X, channel_id, sample_id, Xtotal, Bins));
    return rcpp_result_gen;
END_RCPP
}
// Update_Theta_Betas_loglinear
arma::mat Update_Theta_Betas_loglinear(arma::mat& R, arma::mat& Theta, arma::mat Betas_start, arma::mat& X, arma::uvec channel_id, arma::uvec sample_id, arma::cube& Xtotal, arma::mat& Bins, int iter);
RcppExport SEXP _SigPoisProcess_Update_Theta_Betas_loglinear(SEXP RSEXP, SEXP ThetaSEXP, SEXP Betas_startSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP XtotalSEXP, SEXP BinsSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Xtotal(XtotalSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Bins(BinsSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_Theta_Betas_loglinear(R, Theta, Betas_start, X, channel_id, sample_id, Xtotal, Bins, iter));
    return rcpp_result_gen;
END_RCPP
}
// PPF_loglinear
List PPF_loglinear(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::vec& Mu_start, arma::mat& X, arma::uvec channel_id, arma::uvec sample_id, arma::cube& Xtotal, arma::mat& Bins, arma::mat& SigPrior, double a, double a0, double b0, double epsilon, std::string method, bool update_Sigs, int maxiter, double tol);
RcppExport SEXP _SigPoisProcess_PPF_loglinear(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP XSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP XtotalSEXP, SEXP BinsSEXP, SEXP SigPriorSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP epsilonSEXP, SEXP methodSEXP, SEXP update_SigsSEXP, SEXP maxiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Xtotal(XtotalSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Bins(BinsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Sigs(update_SigsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(PPF_loglinear(R_start, Theta_start, Betas_start, Mu_start, X, channel_id, sample_id, Xtotal, Bins, SigPrior, a, a0, b0, epsilon, method, update_Sigs, maxiter, tol));
    return rcpp_result_gen;
END_RCPP
}
// sample_Categorical
arma::mat sample_Categorical(arma::mat& Probs);
RcppExport SEXP _SigPoisProcess_sample_Categorical(SEXP ProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Probs(ProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Categorical(Probs));
    return rcpp_result_gen;
END_RCPP
}
// sample_R
arma::mat sample_R(arma::mat& R, arma::mat& W, arma::mat& SigPrior, arma::uvec channel_id);
RcppExport SEXP _SigPoisProcess_sample_R(SEXP RSEXP, SEXP WSEXP, SEXP SigPriorSEXP, SEXP channel_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_R(R, W, SigPrior, channel_id));
    return rcpp_result_gen;
END_RCPP
}
// sample_Theta
arma::mat sample_Theta(arma::mat& Theta, arma::mat& Betas, arma::mat& SignalTrack, arma::vec& bin_weight, arma::mat W, arma::rowvec Mu, double a, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_sample_Theta(SEXP ThetaSEXP, SEXP BetasSEXP, SEXP SignalTrackSEXP, SEXP bin_weightSEXP, SEXP WSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Theta(Theta, Betas, SignalTrack, bin_weight, W, Mu, a, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// sample_Mu
arma::mat sample_Mu(arma::mat& Theta, arma::mat& Betas, double a, double a0, double b0, double Ttot);
RcppExport SEXP _SigPoisProcess_sample_Mu(SEXP ThetaSEXP, SEXP BetasSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP TtotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type Ttot(TtotSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Mu(Theta, Betas, a, a0, b0, Ttot));
    return rcpp_result_gen;
END_RCPP
}
// sample_Betas
arma::cube sample_Betas(arma::mat& Betas_start, arma::mat& W, arma::mat& X, arma::mat& SignalTrack, arma::mat& Theta, arma::vec& bin_weight, arma::rowvec& Mu, int nsamples);
RcppExport SEXP _SigPoisProcess_sample_Betas(SEXP Betas_startSEXP, SEXP WSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP ThetaSEXP, SEXP bin_weightSEXP, SEXP MuSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Betas(Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// sample_Betas_MALA
arma::cube sample_Betas_MALA(arma::mat& Betas_start, arma::mat& W, arma::mat& X, arma::mat& SignalTrack, arma::mat& Theta, arma::vec& bin_weight, arma::cube& PrecondSigma, arma::rowvec& Mu, int nsamples, double eps_step);
RcppExport SEXP _SigPoisProcess_sample_Betas_MALA(SEXP Betas_startSEXP, SEXP WSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP ThetaSEXP, SEXP bin_weightSEXP, SEXP PrecondSigmaSEXP, SEXP MuSEXP, SEXP nsamplesSEXP, SEXP eps_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type PrecondSigma(PrecondSigmaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< double >::type eps_step(eps_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Betas_MALA(Betas_start, W, X, SignalTrack, Theta, bin_weight, PrecondSigma, Mu, nsamples, eps_step));
    return rcpp_result_gen;
END_RCPP
}
// update_Mutation_assignement
void update_Mutation_assignement(arma::mat& W, arma::mat& Probs);
RcppExport SEXP _SigPoisProcess_update_Mutation_assignement(SEXP WSEXP, SEXP ProbsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Probs(ProbsSEXP);
    update_Mutation_assignement(W, Probs);
    return R_NilValue;
END_RCPP
}
// update_Signatures_R
void update_Signatures_R(arma::mat& R, arma::mat& W, arma::mat& SigPrior, arma::mat& Alpha, std::vector<arma::uvec>& channel_indices);
RcppExport SEXP _SigPoisProcess_update_Signatures_R(SEXP RSEXP, SEXP WSEXP, SEXP SigPriorSEXP, SEXP AlphaSEXP, SEXP channel_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec>& >::type channel_indices(channel_indicesSEXP);
    update_Signatures_R(R, W, SigPrior, Alpha, channel_indices);
    return R_NilValue;
END_RCPP
}
// update_Loadings_Theta
void update_Loadings_Theta(arma::mat& Theta, arma::mat& Betas, arma::mat& ExpBetaSignal, arma::vec& bin_weight, arma::mat& W, arma::rowvec& Mu, arma::mat& Smat, arma::rowvec& theta_denom, double a, double Ttot, std::vector<arma::uvec>& sample_indices);
RcppExport SEXP _SigPoisProcess_update_Loadings_Theta(SEXP ThetaSEXP, SEXP BetasSEXP, SEXP ExpBetaSignalSEXP, SEXP bin_weightSEXP, SEXP WSEXP, SEXP MuSEXP, SEXP SmatSEXP, SEXP theta_denomSEXP, SEXP aSEXP, SEXP TtotSEXP, SEXP sample_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ExpBetaSignal(ExpBetaSignalSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Smat(SmatSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type theta_denom(theta_denomSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type Ttot(TtotSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec>& >::type sample_indices(sample_indicesSEXP);
    update_Loadings_Theta(Theta, Betas, ExpBetaSignal, bin_weight, W, Mu, Smat, theta_denom, a, Ttot, sample_indices);
    return R_NilValue;
END_RCPP
}
// update_RelevanceWeights_Mu
void update_RelevanceWeights_Mu(arma::rowvec& Mu, arma::mat& Theta, arma::mat& Betas, arma::rowvec& Betasq, arma::rowvec& Theta_sum, double a, double a0, double b0, double Ttot);
RcppExport SEXP _SigPoisProcess_update_RelevanceWeights_Mu(SEXP MuSEXP, SEXP ThetaSEXP, SEXP BetasSEXP, SEXP BetasqSEXP, SEXP Theta_sumSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP TtotSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Betasq(BetasqSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Theta_sum(Theta_sumSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type Ttot(TtotSEXP);
    update_RelevanceWeights_Mu(Mu, Theta, Betas, Betasq, Theta_sum, a, a0, b0, Ttot);
    return R_NilValue;
END_RCPP
}
// update_Betas_coefficients
void update_Betas_coefficients(arma::mat& Betas, arma::mat& W, arma::rowvec& Mu, arma::mat& Theta, arma::mat& X, arma::mat& SignalTrack, arma::rowvec& bw, arma::vec& betadiff, arma::rowvec& Theta_sum, double it, arma::vec& beta_new, arma::mat& S, arma::cube& Sigmas_adp, arma::mat& MeanBetas, arma::mat& WtX);
RcppExport SEXP _SigPoisProcess_update_Betas_coefficients(SEXP BetasSEXP, SEXP WSEXP, SEXP MuSEXP, SEXP ThetaSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP bwSEXP, SEXP betadiffSEXP, SEXP Theta_sumSEXP, SEXP itSEXP, SEXP beta_newSEXP, SEXP SSEXP, SEXP Sigmas_adpSEXP, SEXP MeanBetasSEXP, SEXP WtXSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type betadiff(betadiffSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Theta_sum(Theta_sumSEXP);
    Rcpp::traits::input_parameter< double >::type it(itSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta_new(beta_newSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Sigmas_adp(Sigmas_adpSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type MeanBetas(MeanBetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type WtX(WtXSEXP);
    update_Betas_coefficients(Betas, W, Mu, Theta, X, SignalTrack, bw, betadiff, Theta_sum, it, beta_new, S, Sigmas_adp, MeanBetas, WtX);
    return R_NilValue;
END_RCPP
}
// update_Betas_coefficients_MALA
void update_Betas_coefficients_MALA(arma::mat& Betas, arma::mat& WtX, arma::mat& SignalTrack, arma::rowvec& Theta_sum, arma::vec& beta_new, arma::vec& bin_weight, arma::rowvec& bw, arma::rowvec& Mu, double eps_step, arma::mat& ExpBetaSignal, arma::vec& ExpSignalBeta_new, arma::cube& PrecondSigma, arma::cube& Cholesky, arma::cube& Inverse, arma::vec& logGrad_old, arma::vec& logGrad_new);
RcppExport SEXP _SigPoisProcess_update_Betas_coefficients_MALA(SEXP BetasSEXP, SEXP WtXSEXP, SEXP SignalTrackSEXP, SEXP Theta_sumSEXP, SEXP beta_newSEXP, SEXP bin_weightSEXP, SEXP bwSEXP, SEXP MuSEXP, SEXP eps_stepSEXP, SEXP ExpBetaSignalSEXP, SEXP ExpSignalBeta_newSEXP, SEXP PrecondSigmaSEXP, SEXP CholeskySEXP, SEXP InverseSEXP, SEXP logGrad_oldSEXP, SEXP logGrad_newSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type WtX(WtXSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Theta_sum(Theta_sumSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta_new(beta_newSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type bw(bwSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type eps_step(eps_stepSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ExpBetaSignal(ExpBetaSignalSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type ExpSignalBeta_new(ExpSignalBeta_newSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type PrecondSigma(PrecondSigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Cholesky(CholeskySEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Inverse(InverseSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type logGrad_old(logGrad_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type logGrad_new(logGrad_newSEXP);
    update_Betas_coefficients_MALA(Betas, WtX, SignalTrack, Theta_sum, beta_new, bin_weight, bw, Mu, eps_step, ExpBetaSignal, ExpSignalBeta_new, PrecondSigma, Cholesky, Inverse, logGrad_old, logGrad_new);
    return R_NilValue;
END_RCPP
}
// PoissonProcess_Bayes_MALA
List PoissonProcess_Bayes_MALA(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::rowvec& Mu_start, arma::mat& X, arma::mat& SignalTrack, arma::vec& bin_weight, int nsamples, int burn_in, arma::uvec channel_id, arma::uvec sample_id, arma::mat SigPrior, arma::cube& PrecondSigma, double eps_step, bool update_R, bool update_Theta, bool update_Betas, double a, double a0, double b0);
RcppExport SEXP _SigPoisProcess_PoissonProcess_Bayes_MALA(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP bin_weightSEXP, SEXP nsamplesSEXP, SEXP burn_inSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP PrecondSigmaSEXP, SEXP eps_stepSEXP, SEXP update_RSEXP, SEXP update_ThetaSEXP, SEXP update_BetasSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type PrecondSigma(PrecondSigmaSEXP);
    Rcpp::traits::input_parameter< double >::type eps_step(eps_stepSEXP);
    Rcpp::traits::input_parameter< bool >::type update_R(update_RSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Theta(update_ThetaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Betas(update_BetasSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(PoissonProcess_Bayes_MALA(R_start, Theta_start, Betas_start, Mu_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, PrecondSigma, eps_step, update_R, update_Theta, update_Betas, a, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// PoissonProcess_Bayes
List PoissonProcess_Bayes(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::mat& X, arma::mat& SignalTrack, arma::vec& bin_weight, int nsamples, int burn_in, arma::uvec channel_id, arma::uvec sample_id, arma::mat SigPrior, bool update_R, bool update_Theta, bool update_Betas, double a, double a0, double b0);
RcppExport SEXP _SigPoisProcess_PoissonProcess_Bayes(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP bin_weightSEXP, SEXP nsamplesSEXP, SEXP burn_inSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP update_RSEXP, SEXP update_ThetaSEXP, SEXP update_BetasSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type update_R(update_RSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Theta(update_ThetaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Betas(update_BetasSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(PoissonProcess_Bayes(R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R, update_Theta, update_Betas, a, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// sample_CategoricalCN
arma::mat sample_CategoricalCN(arma::mat& Probs);
RcppExport SEXP _SigPoisProcess_sample_CategoricalCN(SEXP ProbsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Probs(ProbsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_CategoricalCN(Probs));
    return rcpp_result_gen;
END_RCPP
}
// sample_RCN
arma::mat sample_RCN(arma::mat& R, arma::mat& W, arma::mat& SigPrior, arma::uvec channel_id);
RcppExport SEXP _SigPoisProcess_sample_RCN(SEXP RSEXP, SEXP WSEXP, SEXP SigPriorSEXP, SEXP channel_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_RCN(R, W, SigPrior, channel_id));
    return rcpp_result_gen;
END_RCPP
}
// sample_ThetaCN
arma::mat sample_ThetaCN(arma::mat& Theta, arma::mat& Betas, arma::mat& SignalTrack, arma::mat& CopyTrack_t, arma::rowvec& CopyTot, arma::mat W, arma::rowvec Mu, double a, arma::uvec sample_id);
RcppExport SEXP _SigPoisProcess_sample_ThetaCN(SEXP ThetaSEXP, SEXP BetasSEXP, SEXP SignalTrackSEXP, SEXP CopyTrack_tSEXP, SEXP CopyTotSEXP, SEXP WSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack_t(CopyTrack_tSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type CopyTot(CopyTotSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_ThetaCN(Theta, Betas, SignalTrack, CopyTrack_t, CopyTot, W, Mu, a, sample_id));
    return rcpp_result_gen;
END_RCPP
}
// sample_MuCN
arma::rowvec sample_MuCN(arma::mat& Theta, double a, double a0, double b0, arma::rowvec& CopyTot);
RcppExport SEXP _SigPoisProcess_sample_MuCN(SEXP ThetaSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP CopyTotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type CopyTot(CopyTotSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_MuCN(Theta, a, a0, b0, CopyTot));
    return rcpp_result_gen;
END_RCPP
}
// sample_Sigma2CN
arma::rowvec sample_Sigma2CN(arma::mat& Betas, double c0, double d0);
RcppExport SEXP _SigPoisProcess_sample_Sigma2CN(SEXP BetasSEXP, SEXP c0SEXP, SEXP d0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Sigma2CN(Betas, c0, d0));
    return rcpp_result_gen;
END_RCPP
}
// sample_BetasCN
arma::cube sample_BetasCN(arma::mat& Betas_start, arma::mat& W, arma::mat& X, arma::mat& SignalTrack, arma::mat& Theta, arma::vec& bin_weight, arma::rowvec& Mu, int nsamples);
RcppExport SEXP _SigPoisProcess_sample_BetasCN(SEXP Betas_startSEXP, SEXP WSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP ThetaSEXP, SEXP bin_weightSEXP, SEXP MuSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_BetasCN(Betas_start, W, X, SignalTrack, Theta, bin_weight, Mu, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// update_Mutation_assignementCN
void update_Mutation_assignementCN(arma::mat& W, arma::mat& Probs);
RcppExport SEXP _SigPoisProcess_update_Mutation_assignementCN(SEXP WSEXP, SEXP ProbsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Probs(ProbsSEXP);
    update_Mutation_assignementCN(W, Probs);
    return R_NilValue;
END_RCPP
}
// update_Signatures_RCN
void update_Signatures_RCN(arma::mat& R, arma::mat& W, arma::mat& SigPrior, arma::mat& Alpha, std::vector<arma::uvec>& channel_indices);
RcppExport SEXP _SigPoisProcess_update_Signatures_RCN(SEXP RSEXP, SEXP WSEXP, SEXP SigPriorSEXP, SEXP AlphaSEXP, SEXP channel_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec>& >::type channel_indices(channel_indicesSEXP);
    update_Signatures_RCN(R, W, SigPrior, Alpha, channel_indices);
    return R_NilValue;
END_RCPP
}
// update_Activities_ThetaCN
void update_Activities_ThetaCN(arma::mat& Theta, arma::mat& ExpBetaSignal, arma::mat& CopyTrack_t, arma::rowvec& CopyTot, arma::mat& W, arma::rowvec& Mu, arma::mat& Smat, double a, std::vector<arma::uvec>& sample_indices);
RcppExport SEXP _SigPoisProcess_update_Activities_ThetaCN(SEXP ThetaSEXP, SEXP ExpBetaSignalSEXP, SEXP CopyTrack_tSEXP, SEXP CopyTotSEXP, SEXP WSEXP, SEXP MuSEXP, SEXP SmatSEXP, SEXP aSEXP, SEXP sample_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ExpBetaSignal(ExpBetaSignalSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack_t(CopyTrack_tSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type CopyTot(CopyTotSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Smat(SmatSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::uvec>& >::type sample_indices(sample_indicesSEXP);
    update_Activities_ThetaCN(Theta, ExpBetaSignal, CopyTrack_t, CopyTot, W, Mu, Smat, a, sample_indices);
    return R_NilValue;
END_RCPP
}
// update_RelevanceWeights_MuCN
void update_RelevanceWeights_MuCN(arma::rowvec& Mu, arma::mat& Theta, arma::rowvec& CopyTot, double a, double a0, double b0);
RcppExport SEXP _SigPoisProcess_update_RelevanceWeights_MuCN(SEXP MuSEXP, SEXP ThetaSEXP, SEXP CopyTotSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type CopyTot(CopyTotSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    update_RelevanceWeights_MuCN(Mu, Theta, CopyTot, a, a0, b0);
    return R_NilValue;
END_RCPP
}
// update_Variances_Sigma2
void update_Variances_Sigma2(arma::rowvec& Sigma2, arma::mat& Betas, double c0, double d0);
RcppExport SEXP _SigPoisProcess_update_Variances_Sigma2(SEXP Sigma2SEXP, SEXP BetasSEXP, SEXP c0SEXP, SEXP d0SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec& >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    update_Variances_Sigma2(Sigma2, Betas, c0, d0);
    return R_NilValue;
END_RCPP
}
// EllipticalSlice
arma::vec EllipticalSlice(int k, arma::vec& beta0, arma::mat& WtX, arma::rowvec& Sigma2, arma::mat& Theta, arma::mat& SignalTrack, arma::mat& CopyTrack_t);
RcppExport SEXP _SigPoisProcess_EllipticalSlice(SEXP kSEXP, SEXP beta0SEXP, SEXP WtXSEXP, SEXP Sigma2SEXP, SEXP ThetaSEXP, SEXP SignalTrackSEXP, SEXP CopyTrack_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type WtX(WtXSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack_t(CopyTrack_tSEXP);
    rcpp_result_gen = Rcpp::wrap(EllipticalSlice(k, beta0, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t));
    return rcpp_result_gen;
END_RCPP
}
// update_Betas_EllipticalSlice
void update_Betas_EllipticalSlice(arma::mat& Betas, arma::mat& WtX, arma::rowvec& Sigma2, arma::mat& Theta, arma::mat& SignalTrack, arma::mat& CopyTrack_t);
RcppExport SEXP _SigPoisProcess_update_Betas_EllipticalSlice(SEXP BetasSEXP, SEXP WtXSEXP, SEXP Sigma2SEXP, SEXP ThetaSEXP, SEXP SignalTrackSEXP, SEXP CopyTrack_tSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type WtX(WtXSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Sigma2(Sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack_t(CopyTrack_tSEXP);
    update_Betas_EllipticalSlice(Betas, WtX, Sigma2, Theta, SignalTrack, CopyTrack_t);
    return R_NilValue;
END_RCPP
}
// PoissonProcess_BayesCN
List PoissonProcess_BayesCN(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::rowvec& Mu_start, arma::rowvec& Sigma2_start, arma::mat& X, arma::mat& SignalTrack, arma::mat& CopyTrack, int nsamples, int burn_in, arma::uvec channel_id, arma::uvec sample_id, arma::mat SigPrior, bool update_R, bool update_Theta, bool update_Betas, double a, double a0, double b0, double c0, double d0);
RcppExport SEXP _SigPoisProcess_PoissonProcess_BayesCN(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP Sigma2_startSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP CopyTrackSEXP, SEXP nsamplesSEXP, SEXP burn_inSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP update_RSEXP, SEXP update_ThetaSEXP, SEXP update_BetasSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP c0SEXP, SEXP d0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Sigma2_start(Sigma2_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack(CopyTrackSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< bool >::type update_R(update_RSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Theta(update_ThetaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Betas(update_BetasSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    rcpp_result_gen = Rcpp::wrap(PoissonProcess_BayesCN(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, nsamples, burn_in, channel_id, sample_id, SigPrior, update_R, update_Theta, update_Betas, a, a0, b0, c0, d0));
    return rcpp_result_gen;
END_RCPP
}
// PoissonProcess_optim
List PoissonProcess_optim(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::mat& X, arma::mat& SignalTrack, arma::vec& bin_weight, arma::uvec channel_id, arma::uvec sample_id, arma::mat SigPrior, std::string method, std::string shrinkage, double a, double a0, double b0, double c0, double d0, double rho, bool update_R, bool update_Theta, bool update_Betas, int n_iter_betas, int maxiter, double tol, bool correct_betas);
RcppExport SEXP _SigPoisProcess_PoissonProcess_optim(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP bin_weightSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP methodSEXP, SEXP shrinkageSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP c0SEXP, SEXP d0SEXP, SEXP rhoSEXP, SEXP update_RSEXP, SEXP update_ThetaSEXP, SEXP update_BetasSEXP, SEXP n_iter_betasSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP correct_betasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type bin_weight(bin_weightSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type shrinkage(shrinkageSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type update_R(update_RSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Theta(update_ThetaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Betas(update_BetasSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter_betas(n_iter_betasSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type correct_betas(correct_betasSEXP);
    rcpp_result_gen = Rcpp::wrap(PoissonProcess_optim(R_start, Theta_start, Betas_start, X, SignalTrack, bin_weight, channel_id, sample_id, SigPrior, method, shrinkage, a, a0, b0, c0, d0, rho, update_R, update_Theta, update_Betas, n_iter_betas, maxiter, tol, correct_betas));
    return rcpp_result_gen;
END_RCPP
}
// PoissonProcess_optim_CN
List PoissonProcess_optim_CN(arma::mat& R_start, arma::mat& Theta_start, arma::mat& Betas_start, arma::rowvec& Mu_start, arma::rowvec& Sigma2_start, arma::mat& X, arma::mat& SignalTrack, arma::mat& CopyTrack, arma::uvec channel_id, arma::uvec sample_id, arma::mat SigPrior, std::string method, std::string shrinkage, double a, double a0, double b0, double c0, double d0, bool update_R, bool update_Theta, bool update_Betas, int n_iter_betas, double rho, int maxiter, double tol, bool correct_betas);
RcppExport SEXP _SigPoisProcess_PoissonProcess_optim_CN(SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Betas_startSEXP, SEXP Mu_startSEXP, SEXP Sigma2_startSEXP, SEXP XSEXP, SEXP SignalTrackSEXP, SEXP CopyTrackSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP, SEXP SigPriorSEXP, SEXP methodSEXP, SEXP shrinkageSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP c0SEXP, SEXP d0SEXP, SEXP update_RSEXP, SEXP update_ThetaSEXP, SEXP update_BetasSEXP, SEXP n_iter_betasSEXP, SEXP rhoSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP correct_betasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas_start(Betas_startSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::rowvec& >::type Sigma2_start(Sigma2_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack(CopyTrackSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type sample_id(sample_idSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type shrinkage(shrinkageSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< bool >::type update_R(update_RSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Theta(update_ThetaSEXP);
    Rcpp::traits::input_parameter< bool >::type update_Betas(update_BetasSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter_betas(n_iter_betasSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type correct_betas(correct_betasSEXP);
    rcpp_result_gen = Rcpp::wrap(PoissonProcess_optim_CN(R_start, Theta_start, Betas_start, Mu_start, Sigma2_start, X, SignalTrack, CopyTrack, channel_id, sample_id, SigPrior, method, shrinkage, a, a0, b0, c0, d0, update_R, update_Theta, update_Betas, n_iter_betas, rho, maxiter, tol, correct_betas));
    return rcpp_result_gen;
END_RCPP
}
// Reconstruct_Lambda
arma::mat Reconstruct_Lambda(arma::mat& SignalTrack, arma::mat& CopyTrack, arma::mat& R, arma::mat& Theta, arma::mat& Betas);
RcppExport SEXP _SigPoisProcess_Reconstruct_Lambda(SEXP SignalTrackSEXP, SEXP CopyTrackSEXP, SEXP RSEXP, SEXP ThetaSEXP, SEXP BetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack(CopyTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    rcpp_result_gen = Rcpp::wrap(Reconstruct_Lambda(SignalTrack, CopyTrack, R, Theta, Betas));
    return rcpp_result_gen;
END_RCPP
}
// Reconstruct_CountMatrix
arma::mat Reconstruct_CountMatrix(arma::mat& SignalTrack, arma::mat& CopyTrack, arma::mat& R, arma::mat& Theta, arma::mat& Betas);
RcppExport SEXP _SigPoisProcess_Reconstruct_CountMatrix(SEXP SignalTrackSEXP, SEXP CopyTrackSEXP, SEXP RSEXP, SEXP ThetaSEXP, SEXP BetasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type SignalTrack(SignalTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type CopyTrack(CopyTrackSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Betas(BetasSEXP);
    rcpp_result_gen = Rcpp::wrap(Reconstruct_CountMatrix(SignalTrack, CopyTrack, R, Theta, Betas));
    return rcpp_result_gen;
END_RCPP
}
// eval_logPosterior
double eval_logPosterior(arma::mat& X, arma::mat& R, arma::mat& Theta, arma::vec& Mu, double a, double a0, double b0, arma::mat& SigPrior);
RcppExport SEXP _SigPoisProcess_eval_logPosterior(SEXP XSEXP, SEXP RSEXP, SEXP ThetaSEXP, SEXP MuSEXP, SEXP aSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP SigPriorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_logPosterior(X, R, Theta, Mu, a, a0, b0, SigPrior));
    return rcpp_result_gen;
END_RCPP
}
// compute_CompressiveNMF_MAP
List compute_CompressiveNMF_MAP(arma::mat X, arma::mat R_start, arma::mat Theta_start, arma::vec Mu_start, arma::mat& SigPrior, double a0, double b0, double a, int maxiter, double tol, bool use_logpost_for_convergence);
RcppExport SEXP _SigPoisProcess_compute_CompressiveNMF_MAP(SEXP XSEXP, SEXP R_startSEXP, SEXP Theta_startSEXP, SEXP Mu_startSEXP, SEXP SigPriorSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP aSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP use_logpost_for_convergenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R_start(R_startSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta_start(Theta_startSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mu_start(Mu_startSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type SigPrior(SigPriorSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type use_logpost_for_convergence(use_logpost_for_convergenceSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_CompressiveNMF_MAP(X, R_start, Theta_start, Mu_start, SigPrior, a0, b0, a, maxiter, tol, use_logpost_for_convergence));
    return rcpp_result_gen;
END_RCPP
}
// sample_table_cpp
arma::uvec sample_table_cpp(arma::mat& tab);
RcppExport SEXP _SigPoisProcess_sample_table_cpp(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type tab(tabSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_table_cpp(tab));
    return rcpp_result_gen;
END_RCPP
}
// sample_Counts_cpp
List sample_Counts_cpp(arma::mat& X, arma::mat& R, arma::cube& Betas, arma::uvec& channel_Id, arma::uvec& sample_Id);
RcppExport SEXP _SigPoisProcess_sample_Counts_cpp(SEXP XSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP channel_IdSEXP, SEXP sample_IdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_Id(channel_IdSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_Id(sample_IdSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Counts_cpp(X, R, Betas, channel_Id, sample_Id));
    return rcpp_result_gen;
END_RCPP
}
// calculate_Sig_covariate_prob
List calculate_Sig_covariate_prob(arma::mat& X, arma::mat& R, arma::cube& Betas, arma::uvec& channel_id, arma::uvec& sample_id);
RcppExport SEXP _SigPoisProcess_calculate_Sig_covariate_prob(SEXP XSEXP, SEXP RSEXP, SEXP BetasSEXP, SEXP channel_idSEXP, SEXP sample_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Betas(BetasSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type channel_id(channel_idSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type sample_id(sample_idSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_Sig_covariate_prob(X, R, Betas, channel_id, sample_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SigPoisProcess_Update_Phi", (DL_FUNC) &_SigPoisProcess_Update_Phi, 7},
    {"_SigPoisProcess_Update_alpha_r", (DL_FUNC) &_SigPoisProcess_Update_alpha_r, 5},
    {"_SigPoisProcess_Update_ab_beta", (DL_FUNC) &_SigPoisProcess_Update_ab_beta, 9},
    {"_SigPoisProcess_Update_ab_mu", (DL_FUNC) &_SigPoisProcess_Update_ab_mu, 7},
    {"_SigPoisProcess_InhomogeneousPoissonNMF_CAVI", (DL_FUNC) &_SigPoisProcess_InhomogeneousPoissonNMF_CAVI, 16},
    {"_SigPoisProcess_build_X_field", (DL_FUNC) &_SigPoisProcess_build_X_field, 5},
    {"_SigPoisProcess_Update_Signatures_MAP", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MAP, 4},
    {"_SigPoisProcess_Update_Signatures_MAP2", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MAP2, 6},
    {"_SigPoisProcess_Update_Betas_MAP", (DL_FUNC) &_SigPoisProcess_Update_Betas_MAP, 7},
    {"_SigPoisProcess_Update_Betas_MAP2", (DL_FUNC) &_SigPoisProcess_Update_Betas_MAP2, 9},
    {"_SigPoisProcess_Update_Mu", (DL_FUNC) &_SigPoisProcess_Update_Mu, 7},
    {"_SigPoisProcess_compute_SigPoisProcess_logPost", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logPost, 10},
    {"_SigPoisProcess_compute_SigPoisProcess_logPost2", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logPost2, 12},
    {"_SigPoisProcess_merge_similar_signatures", (DL_FUNC) &_SigPoisProcess_merge_similar_signatures, 11},
    {"_SigPoisProcess_compute_SigPoisProcess_MAP", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MAP, 17},
    {"_SigPoisProcess_compute_SigPoisProcess_MAP_Nest", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MAP_Nest, 14},
    {"_SigPoisProcess_Update_Signatures_MLE", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MLE, 3},
    {"_SigPoisProcess_Update_Betas_MLE", (DL_FUNC) &_SigPoisProcess_Update_Betas_MLE, 4},
    {"_SigPoisProcess_compute_SigPoisProcess_logLik", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_logLik, 4},
    {"_SigPoisProcess_compute_SigPoisProcess_MLE", (DL_FUNC) &_SigPoisProcess_compute_SigPoisProcess_MLE, 8},
    {"_SigPoisProcess_build_X_field2", (DL_FUNC) &_SigPoisProcess_build_X_field2, 5},
    {"_SigPoisProcess_compute_expXtB_field", (DL_FUNC) &_SigPoisProcess_compute_expXtB_field, 6},
    {"_SigPoisProcess_Update_Signatures_MLE_loglinear2", (DL_FUNC) &_SigPoisProcess_Update_Signatures_MLE_loglinear2, 6},
    {"_SigPoisProcess_Update_Theta_MLE_loglinear", (DL_FUNC) &_SigPoisProcess_Update_Theta_MLE_loglinear, 8},
    {"_SigPoisProcess_Update_Theta_Betas_loglinear", (DL_FUNC) &_SigPoisProcess_Update_Theta_Betas_loglinear, 9},
    {"_SigPoisProcess_PPF_loglinear", (DL_FUNC) &_SigPoisProcess_PPF_loglinear, 18},
    {"_SigPoisProcess_sample_Categorical", (DL_FUNC) &_SigPoisProcess_sample_Categorical, 1},
    {"_SigPoisProcess_sample_R", (DL_FUNC) &_SigPoisProcess_sample_R, 4},
    {"_SigPoisProcess_sample_Theta", (DL_FUNC) &_SigPoisProcess_sample_Theta, 8},
    {"_SigPoisProcess_sample_Mu", (DL_FUNC) &_SigPoisProcess_sample_Mu, 6},
    {"_SigPoisProcess_sample_Betas", (DL_FUNC) &_SigPoisProcess_sample_Betas, 8},
    {"_SigPoisProcess_sample_Betas_MALA", (DL_FUNC) &_SigPoisProcess_sample_Betas_MALA, 10},
    {"_SigPoisProcess_update_Mutation_assignement", (DL_FUNC) &_SigPoisProcess_update_Mutation_assignement, 2},
    {"_SigPoisProcess_update_Signatures_R", (DL_FUNC) &_SigPoisProcess_update_Signatures_R, 5},
    {"_SigPoisProcess_update_Loadings_Theta", (DL_FUNC) &_SigPoisProcess_update_Loadings_Theta, 11},
    {"_SigPoisProcess_update_RelevanceWeights_Mu", (DL_FUNC) &_SigPoisProcess_update_RelevanceWeights_Mu, 9},
    {"_SigPoisProcess_update_Betas_coefficients", (DL_FUNC) &_SigPoisProcess_update_Betas_coefficients, 15},
    {"_SigPoisProcess_update_Betas_coefficients_MALA", (DL_FUNC) &_SigPoisProcess_update_Betas_coefficients_MALA, 16},
    {"_SigPoisProcess_PoissonProcess_Bayes_MALA", (DL_FUNC) &_SigPoisProcess_PoissonProcess_Bayes_MALA, 20},
    {"_SigPoisProcess_PoissonProcess_Bayes", (DL_FUNC) &_SigPoisProcess_PoissonProcess_Bayes, 17},
    {"_SigPoisProcess_sample_CategoricalCN", (DL_FUNC) &_SigPoisProcess_sample_CategoricalCN, 1},
    {"_SigPoisProcess_sample_RCN", (DL_FUNC) &_SigPoisProcess_sample_RCN, 4},
    {"_SigPoisProcess_sample_ThetaCN", (DL_FUNC) &_SigPoisProcess_sample_ThetaCN, 9},
    {"_SigPoisProcess_sample_MuCN", (DL_FUNC) &_SigPoisProcess_sample_MuCN, 5},
    {"_SigPoisProcess_sample_Sigma2CN", (DL_FUNC) &_SigPoisProcess_sample_Sigma2CN, 3},
    {"_SigPoisProcess_sample_BetasCN", (DL_FUNC) &_SigPoisProcess_sample_BetasCN, 8},
    {"_SigPoisProcess_update_Mutation_assignementCN", (DL_FUNC) &_SigPoisProcess_update_Mutation_assignementCN, 2},
    {"_SigPoisProcess_update_Signatures_RCN", (DL_FUNC) &_SigPoisProcess_update_Signatures_RCN, 5},
    {"_SigPoisProcess_update_Activities_ThetaCN", (DL_FUNC) &_SigPoisProcess_update_Activities_ThetaCN, 9},
    {"_SigPoisProcess_update_RelevanceWeights_MuCN", (DL_FUNC) &_SigPoisProcess_update_RelevanceWeights_MuCN, 6},
    {"_SigPoisProcess_update_Variances_Sigma2", (DL_FUNC) &_SigPoisProcess_update_Variances_Sigma2, 4},
    {"_SigPoisProcess_EllipticalSlice", (DL_FUNC) &_SigPoisProcess_EllipticalSlice, 7},
    {"_SigPoisProcess_update_Betas_EllipticalSlice", (DL_FUNC) &_SigPoisProcess_update_Betas_EllipticalSlice, 6},
    {"_SigPoisProcess_PoissonProcess_BayesCN", (DL_FUNC) &_SigPoisProcess_PoissonProcess_BayesCN, 21},
    {"_SigPoisProcess_PoissonProcess_optim", (DL_FUNC) &_SigPoisProcess_PoissonProcess_optim, 24},
    {"_SigPoisProcess_PoissonProcess_optim_CN", (DL_FUNC) &_SigPoisProcess_PoissonProcess_optim_CN, 26},
    {"_SigPoisProcess_Reconstruct_Lambda", (DL_FUNC) &_SigPoisProcess_Reconstruct_Lambda, 5},
    {"_SigPoisProcess_Reconstruct_CountMatrix", (DL_FUNC) &_SigPoisProcess_Reconstruct_CountMatrix, 5},
    {"_SigPoisProcess_eval_logPosterior", (DL_FUNC) &_SigPoisProcess_eval_logPosterior, 8},
    {"_SigPoisProcess_compute_CompressiveNMF_MAP", (DL_FUNC) &_SigPoisProcess_compute_CompressiveNMF_MAP, 11},
    {"_SigPoisProcess_sample_table_cpp", (DL_FUNC) &_SigPoisProcess_sample_table_cpp, 1},
    {"_SigPoisProcess_sample_Counts_cpp", (DL_FUNC) &_SigPoisProcess_sample_Counts_cpp, 5},
    {"_SigPoisProcess_calculate_Sig_covariate_prob", (DL_FUNC) &_SigPoisProcess_calculate_Sig_covariate_prob, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SigPoisProcess(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
